name: Build & Deploy
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Running Tests & Deployment[LIVE]
        uses: actions/checkout@v2
      - run: |
          touch .env
          echo REACT_APP_LOCAL_URL="https://liuyangtong.io:8085" >> .env
          echo REACT_APP_PRODUCTION_URL="https://liuyangtong.io:8085" >> .env
          echo REACT_APP_STAGING_URL="https://liuyangtong.io:8085" >> .env
          echo REACT_APP_HOST="https://liuyangtong.io:8085" >> .env
          echo REACT_APP_FACEBOOK_APP_ID="1072961700221581" >> .env         
          echo REACT_APP_SENTRY_DSN="https://ca91fc00f47049b39361ea4715ca4fa1@o1137297.ingest.sentry.io/6189727" >> .env
          echo REACT_APP__SENTRY_ENV="local" >> .env
          echo FAST_REFRESH="false" >> .env
          echo PORT="3000" >> .env
          cat .env
      # - run: npm install
      # - run: npm run test
      - uses: appleboy/ssh-action@v0.1.2
        with:
          host: 137.184.35.67 # IP address of the server you wish to ssh into
          password: d82540cd6e6338a84c4f48fbf1
          username: root # User of the server you want to ssh into
          script: |
            cd Tutor-Platform-Front
            git stash
            git pull
            npm i
            pm2 restart front-live
